### ISSUE TITLE
Rename ifbcatsandbox to ifbcat in sources ?

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#109]
Hi @joncison, but also @thomasrosnet @mrcrony

The project have been renamed, but "sandbox" remains in the sources, I can rename to remove sandbox (tested on my computer). The operation for each of you would be then to delete the data base and re run a `python manage.py migrate`. I thinks it is kind of now or never as for now there is no real data in production db, only tests.

So ? go no-go ?

Cheers

**Comment by joncison** [comment]
Yeah - @hmenager and I looked at this, but it seemed (to me at least :) that to rename a Djano app is complicated ... prob. easier if the database is just deleted though.  It def. needs to happen!

**Comment by bryan-brancotte** [comment]
I can do it within minutes, just waiting for your go

**Comment by bryan-brancotte** [comment]
And yes, a hard task if you want to preserve data, I our case we don't have real data yet so it is very easy

**Comment by joncison** [comment]
OK, cool.

Go for it!

We may need to reinstate some things though ... Community and
ElixirPlatform if I recall.

**Comment by bryan-brancotte** [comment]
Hi @joncison @thomasrosnet @mrcrony @hmenager 

I renamed ifbcatsandbox to ifbcat, the production db is now empty (but with keyword `Tartiflette` :wink: ), you have to re-create your accounts (cf https://github.com/IFB-ElixirFr/ifbcat#create-a-superuser)

On your local computer :
 * if you used `./manage.py runserver` you have to delete db.sqlite.
 * if you used `docker-compose ip` you have to delete /var/ifbcat/db_data/

**Comment by joncison** [comment]
Great job @bryan-brancotte !
