### ISSUE TITLE
short-name mapped from name

### ISSUE THREAD

**Issue by nicolas-geysse** [IFB-ElixirFr/ifbcat#110]
Hi,
As an improvement UX design, having the short-name mapped from the typed name filled while going to next tab (then could be modified manually for optimising SEF would be nice)

**Comment by bryan-brancotte** [comment]
You mean when filling the form in the /api/.../ ?

**Comment by mrcrony** [comment]
Yes, into the view:
/admin/xxx/event/3/change/

But it's a really low priority...

**Comment by bryan-brancotte** [comment]
I though I understood what you said, but I did not sorry. COuld you give me an example of what we have and what you would want to have ?

**Comment by mrcrony** [comment]
What we have : you fill the name, the shot-name needs to be filled
<img width="401" alt="Capture d’écran 2020-09-11 à 16 31 05" src="https://user-images.githubusercontent.com/8360521/92938002-52ad4380-f44c-11ea-8b63-57368fd1ee25.png">

What would be more UX friendly, we fill the name, then on tabulation to the next field, the name goes with a regex into the short-name field. (you still may change it if needed after that) 
<img width="346" alt="Capture d’écran 2020-09-11 à 16 31 32" src="https://user-images.githubusercontent.com/8360521/92938029-5c36ab80-f44c-11ea-96cd-9db1d04236c4.png">

**Comment by bryan-brancotte** [comment]
`shortName` is only used by user, api use pk, so closing.
