### ISSUE TITLE
Add organisedBy field to Event model 

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#121]
organisedBy 
A bioinformatics team that organised the event. 
0 to many

complication is that target of organisedBy could be (at least as currently defined) Team, BioinformaticsTeam or Organisation 

if (as I think) any of these 3 entities can indeed be the organiser, we may need 3 separate fields

cc @hmenager

**Comment by bryan-brancotte** [comment]
Hi

For now I havn't found a way to put all three into one field in the api.

In the mean time I have issue as if we associate a bioinfoteam, but render it as a team in the api, le link is http://127.0.0.1:8092/api/team/bioinformatics%20team/ and not http://127.0.0.1:8092/api/bioinformaticsteam/bioinformatics%20team/". In http://127.0.0.1:8092/api/team/bioinformatics%20team/ we for example don't see the topics.

I'll keep searching

**Comment by joncison** [comment]
Thanks for looking Bryan, if we have to end up with something like this, it's not the end of the world (just a bit ugly):
*organisedByTeam
*organisedByBioinformaticsTeam
*organisedByOrganisation

**Comment by bryan-brancotte** [comment]
That is also the only solution I see for now

An other solution would be to develop a new API field that merge multiple attribute, but I don't see how, and it might cost a lot of time

**Comment by joncison** [comment]
I think the above would do for now - if a neater solution presents itself in due course, then great.
