### ISSUE TITLE
Losing support of sqlite ?

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#127]
Hi @joncison @hmenager 

In order to write easily code I would like to drop sqlite as we run pgsql in production. Indeed I use unaccent, a pg module that search while ignoring accent in word. I use use for keyword lookup, during import, ...

I can continu to support both, but I am wondering why we should as we only need to do a `docker-compose run db` and the db is up.

**Comment by joncison** [comment]
This is fine by me Bryan.
