### ISSUE TITLE
Problem with IFB profile Mandatory DOI for Primary publication

### ISSUE THREAD

**Issue by thomasrosnet** [IFB-ElixirFr/ifbcat#128]
Some tools from biotools don't have a DOI but a PMID or PMCID instead.

We could:
- Not add them into the catalogue
- ask to the contact to add the DOI on biotools
- use an automatic tool to convert PMID to DOI such as E-Utils from NCBI

**Comment by jvanheld** [comment]
Is there a way to automatically obtain DOIs from PMIDs ?
In principle it should be feasible, maybe even with the PUBMED API

**Comment by bryan-brancotte** [comment]
to continue on the e-utils option:

```python
from Bio import Entrez
def get_doi_from_pmid(pmid):
    with Entrez.efetch(db="pubmed", id=str(pmid), rettype="xml", retmode="text") as handle:
        d = Entrez.read(handle)
        for article_id in d["PubmedArticle"][0]["PubmedData"]["ArticleIdList"]:
            if article_id[:2] == "10":
                return article_id

print(get_doi_from_pmid(9719638))
10.1006/jmbi.1998.1947
```

**Comment by thomasrosnet** [comment]
There should be a way to do it automatically, we are looking into it.

**Comment by bryan-brancotte** [comment]
Hi @thomasrosnet 

Do we still have this need, are you aware of a tool with a pubmed id and not a doi ?

**Comment by bryan-brancotte** [comment]
done
