### ISSUE TITLE
Clarify choices for Event types

### ISSUE THREAD

**Issue by guillaumecharbonnier** [IFB-ElixirFr/ifbcat#134]
Currently, the API allows 4 values for Event type:
* Workshop
* Training course
* Meeting
* Conference

The Drupal was allowing 3 values:
* Formation
* Réunion
* Autre

Please see attached the events from Drupal where mapping were not straightforward and my suggestions in column 3.
[proposed_event_type_conversion.xlsx](https://github.com/IFB-ElixirFr/ifbcat/files/5585715/proposed_event_type_conversion.xlsx)

Could you approve or disprove these actions?

- [ ] Add "Other" choice to the API
- [ ] Update the Drupal to fit the 5 choices from the API. Maybe in French to keep consistency with the Drupal field, i.e.
* Formation
* Réunion
* Atelier
* Conférence
* Autre  
- [ ] Update Drupal events with the suggestions from the column 3, then sync export to ifbcat-importdata.

Note to myself:
To add choices for event type in Drupal:
Home » Administration » Structure » Content types » Groupe évènementiel » Manage fields » Type d'évènement » Type d'évènement

**Comment by hmenager** [comment]
I completely approve this. Good call!

**Comment by guillaumecharbonnier** [comment]
Done
