### ISSUE TITLE
Add distinction universitary VS professional for trainingEvent model?

### ISSUE THREAD

**Issue by guillaumecharbonnier** [IFB-ElixirFr/ifbcat#137]
Drupal trainings had this distinction:

* Formation universitaire
* Formation professionnelle

Should we add it to the trainingEvent model?

**Comment by bryan-brancotte** [comment]
solved by https://github.com/IFB-ElixirFr/ifbcat/blob/0f2acc41b3a3b6cd7ced4f1195f4438a41caba89/ifbcat_api/model/misc.py#L182
