### ISSUE TITLE
Error 500 for api/event

### ISSUE THREAD

**Issue by guillaumecharbonnier** [IFB-ElixirFr/ifbcat#139]
I get `error 500` when I try to get to 
https://catalogue.france-bioinformatique.fr/api/event/

Actually, I wanted to check on the prod version if another error occurring locally on my branch was happening too:
Using the search filter on :
http://127.0.0.1:8000/api/event/?offset=520
I get this error 
```
FieldError at /api/event/
Cannot resolve keyword 'costs_cost' into field. Choices are: accessibility, accessibilityNote, city, communities, contactEmail, contactId, contactId_id, contactName, costs, country, dates, description, elixirPlatforms, homepage, hostedBy, id, keywords, logo_url, market, maxParticipants, name, onlineOnly, organisedByBioinformaticsTeams, organisedByOrganisations, organisedByTeams, prerequisites, shortName, sponsoredBy, topics, trainingevent, type, user_profile, user_profile_id, venue
```

**Comment by bryan-brancotte** [comment]
Hi @guillaumecharbonnier 

The error 500 in production is fixed

For the `Cannot resolve keyword 'costs_cost' into field.` I think merging master into your banch will fix the issue, you probably are in this situation :
https://github.com/IFB-ElixirFr/ifbcat/commit/97e84962758e9e728b4c2390eaaf299a44162e1a#diff-da204d51b284f8c37ee05de9f96fce5c57f9bf084ee518d4fbed6b149b6cff78L228

**Comment by guillaumecharbonnier** [comment]
Thanks you are right I have the version before the commit you mention.
