### ISSUE TITLE
authentification avec email insensible à la case

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#147]
Pour l'instant ce n'est pas le cas.

importer tout les compte en minuscule ? 

Comment faire quand quelqu'un se connect avec des majuscule ?

**Comment by Aziguy** [comment]
@bryan-brancotte  I think this issue should be close. Right?

**Comment by bryan-brancotte** [comment]
Indeed ! Using `closing #147` actually close  the issue on merge in gitlab, in github the forme +ing does not work (https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
