### ISSUE TITLE
Keywords are in French for Training events

### ISSUE THREAD

**Issue by olisand** [IFB-ElixirFr/ifbcat#149]
On the page https://catalogue.france-bioinformatique.fr/admin/ifbcat_api/trainingevent/add/, the list of Keywords appear in French whereas other lists to choose from (Topics) are in English.

**Comment by bryan-brancotte** [comment]
Keyword are, for the app, just a string, no translation/multi lang is implemented.

In https://github.com/IFB-ElixirFr/ifbcat/issues/154 @hchiapello suggest that we indicate clearly which language to use.

Do we keep only one language and state that we should use English, or implement multi-language ?

**Comment by bryan-brancotte** [comment]
Suite metting:

### TODO:
 * faire une commande qui pend en entrée un fichier csv avec les traductions fr->en, les appliques, et produit en sortir les keyword qui n'ont pas été trouvé dans les mots en du fichier.
 * Bonus: Utiliser la [fréquence des lettres](https://fr.wikipedia.org/wiki/Fr%C3%A9quence_d%27apparition_des_lettres_en_fran%C3%A7ais) pour deviner la langue des keyword, même si de par la longueur des keyword cela risque de ne pas marcher.

**Comment by bryan-brancotte** [comment]
Je re-ouvre car il va falloir maintenant finir de traduire les keywords, et/ou de valider leur traduction.

https://github.com/IFB-ElixirFr/ifbcat-importdata/blob/master/keywords_english_translate.tsv
