### ISSUE TITLE
AccessibilityNote is mandatory even when Accessibility is set to Public

### ISSUE THREAD

**Issue by olisand** [IFB-ElixirFr/ifbcat#151]
On the page https://catalogue.france-bioinformatique.fr/admin/ifbcat_api/trainingevent/add/, it is mandatory to leave an AccessibilityNote (Comment about the audience a private event is open to and tailored for.), even if Accessibility is set to Public

**Comment by bryan-brancotte** [comment]
No idea, maybe @hmenager will know

**Comment by bryan-brancotte** [comment]
mandatory only when not public

**Comment by bryan-brancotte** [comment]
Following @hchiapello tests, maybe we should set it as optional @hmenager  ?

**Comment by bryan-brancotte** [comment]
@hchiapello accessibilityNote is not mandatory anymore when accessibility is Public
