### ISSUE TITLE
View all sessions of a training

### ISSUE THREAD

**Issue by hchiapello** [IFB-ElixirFr/ifbcat#169]
Would it be possible to have a view of all training sessions of a training in the dashboard of the training catalog ?
Thanks
Helene + Olivier

**Comment by hchiapello** [comment]
To try to explain better : I join a screenshot. I added in red the link I would like to have for each training "View all sessions
![Capture d’écran 2021-10-15 à 17 13 47](https://user-images.githubusercontent.com/25387008/137858968-bf38d475-aa80-4c21-85e7-3fe141b11acd.png)
"
Don't hesitate if you gave any question
Helene

**Comment by bryan-brancotte** [comment]
THanks @hchiapello for answering my question (that I did not event wrote!). This link is easy to add, incomming.
