### ISSUE TITLE
Can new Community, ElixirPlatform, EventCost emerge 

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#17]
In the current implementation, if a new emerge the code have to be updated and re-deployed as they are handled by a `choices=XXXType.choices,`. I think all instances should be created by default within the migration, and if a new emerge the admin has to create a new object in the db. Also common users would not be able to create new entry.

Note that we would have to not use the CreatableSlugRelatedField for this fields, but simply the SlugRelatedField.

**Comment by bryan-brancotte** [comment]
I forgot to ping @joncison  on this matter

**Comment by joncison** [comment]
Thanks Bryan, good question, I should have explained the modelling better beforehand (apologies).

Community, ElixirPlatform and EventCost should indeed be all created upfront (by admin).  Occasionally (rarely) a new community may appear, or we might want to tweak the EventCost - but this doesn't concern the typical user, and would only ever happen very infrequently. 

I _think_ - not certain - that end-users should be able to create an Organisation though.  I recently [created ](https://github.com/joncison/ifbcat-sandbox/commit/201fa3ed26b1564514f7d4a15cf7e8b419aaec4c) an endpoint in the browsable API to allow that.    It's to make registering organisations in the system as easy as possible - there are potentially many organisations to register, so to leave this all to admin could be onerous!   But I'm not certain and would welcome an opinion froom @hmenager.

**Comment by bryan-brancotte** [comment]
By bad, my question was not for Organisation, it is only for model that have a name with choice.

So even if Community, ElixirPlatform and EventCost will rearely see a new one arrive, should we force the code to be updated and deployed, or let the admin handle it ?

**Comment by joncison** [comment]
It's definitely very convenient to be able to edit these options via the Django admin user interface, because there are lots of these controlled vocabularies and I expect some of them will need to change before we go into production.   

Currently we use the text choice e.g. [here](https://github.com/joncison/ifbcat-sandbox/blob/master/ifbcatsandbox_api/serializers.py#L328-L331) for telling the user what the valid values are, in case they enter a wrong one via the "Raw data" method.  And I wonder in future whether we'd have other need for them, e.g. in a future front-end / UI, replacing the use of the browsable API. 

So, I'm not certain. but it might be good to leave them encoded?

**Comment by bryan-brancotte** [comment]
From what you say, I understand that it is important to indicate user what are accepted values, and that is would be convenient for admin to be able to create new one.

I made for #20 an example of what it would be, if a user try to create here a new cost `lol` the server response is
```json
{
    "costs": [
        "Object with cost=lol does not exist."
    ]
}
```
I would work exactly the same for OrganisationField

Also using the pre filling db approch let the db show all the OrganisationField, EventCost, ... before someone create an entry associated to one of the value. For example in my test db I did not have a `Concessions available` so it was not proposed in the browsable api, with #20 all the choices are proposed.

**Comment by bryan-brancotte** [comment]
Here what you get when attempting to create a new OrganisationField when posting an Organisation

pasted data
```
{
    "id": 1,
    "user_profile": 1,
    "name": "Pasteur",
    "description": "qeqsez",
    "homepage": "http://localhost:8092/admin/ifbcatsandbox_api/elixirplatform/add/?_to_field=id&_popup=1",
    "orgid": "012345612",
    "fields": [
        "Computer science","Other field important!"
    ],
    "city": ""
}
```

server response:
```
{
    "fields": [
        "Object with field=Other field important! does not exist."
    ]
}
```

**Comment by bryan-brancotte** [comment]
I took a look at ElixirPlatform and Community, from the information needed I agree with you that the name should rename as is.

so #20 is only for OrganisationField and EventCost
