### ISSUE TITLE
Nettoyage du model Tools

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#181]
Il faut regarder dans le modèle tool quels sont les attributs qui vont être mis à jours depuis bio.tools, et lesquelles ne sont pas changeable. 

Les champs qui ne peuvent être changées seront ensuite à supprimer.

**Comment by bryan-brancotte** [comment]
ping @thomasrosnet si tu as des info sur le mapping vers bio.tools, indique les aussi ici stp

**Comment by bryan-brancotte** [comment]
From @thomasrosnet  : https://biotools.readthedocs.io/en/latest/community_specific_guidelines.html?highlight=france

**Comment by Aziguy** [comment]
Les champs ci-dessous ne sont pas renvoyés par l'api **BioTools** : 
- Logo (présent dans le model `Tool`) ;
- Keywords (présent dans le model `Tool`) ;
- Access_condition (présent dans le model `Tool`) ;
- Contact_support (présent dans le model `Tool`) ;
- Prerequisites (présent dans le model `Tool`) ;
- Primary (présent dans le model `Tool`) ;

Par ailleurs, il y a des champs obligatoires (en vert) comme : 
- Terms of use ;
- General documenttion ;
- Primary contact.

qui ne sont pas présents dans le model `Tool`.

Les champs ci-dessous sont recommandés mais pas présent dans le model : 
- Credided developer ;
- Credided maintainer ;
- Credited institute ;
- Credided funding agency ;
- Training material ;
- Issue tracker ;
- Mailling list ;
- Contribution policy.

**Comment by bryan-brancotte** [comment]
# Retrait des champs en trop:
 * logo (logo des PF utilisé)
 * keywords
 * Access_condition (même s'il y a du contenu, car précision et qualité trop variable)
 * Contact_support
 * Prerequisites
 * Primary

# champs obligatoire 
Ajout

# Champs recommandé

On les laisse de coté, on verra plus tard si besoin

**Comment by bryan-brancotte** [comment]
Bonjour @Aziguy 

Suite discussion, voici ci dessus les actions à faire

**Comment by Aziguy** [comment]
@bryan-brancotte les champs obligatoire ci-dessous doivent être ajoutés au model `Tool` ?
* Terms of use
* General documentation
* Primary contact (est-ce le type_role?)

**Comment by bryan-brancotte** [comment]
Hello @Aziguy Oui il faut les ajouter, merci !

**Comment by bryan-brancotte** [comment]
Hi @hmenager 

@Aziguy raised a good point while working on `load_database` in [#192](https://github.com/IFB-ElixirFr/ifbcat/pull/192/files/0668b782400b00e01de456d2ffd271f8a6ba9d5c..5159b94d5756b331be165229a7220bd5482d51a8#diff-f68b546d6a0d492d4366fe32ee686a43f9a40af51fd2cca399daaf63bf726638): in the catalogue we load databases as a `Tool`. Are databases also accepted in bio.tools ? If no, then we will have to decide how to handle them, and how to rework the Tool model.

**Comment by Aziguy** [comment]
> Hello @Aziguy Oui il faut les ajouter, merci !

J'ai pu constater que :

- [x] On a déjà Primary contact qui est un type role (présent dans la table Tool credits)

- [x] L'api de biotools `license` représente *Terms of use* et dans le modèle tool on a déjà tool_license

- [ ] Il faut donc juste rajouter un champ `documentation` qui correspondrait à *General documentation*

**Comment by bryan-brancotte** [comment]
Les différent type de doc dans bio.tools: https://biotools.readthedocs.io/en/latest/api_usage_guide.html?highlight=type#documentation

**Comment by hmenager** [comment]
Hello, quelques éléments:
- bio.tools n'est pas un registre de bases de données en soit, mais une bonne partie d'entre elles y sont présentes, à partir du moment où elles sont disponibles via un service web quelconque (pas forcément REST etc, un simple CGI les rend légitimes).
- il faudrait voir quelle proportion des DBs à charger sont:
  - dans bio.tools
  - dans FAIRsharing.org (registre qui inclue des DBs)
  ça nous permettrait d'aviser sur cette décision avec des chiffres concrets.

**Comment by bryan-brancotte** [comment]
Dans les données chargée, il y a 47 db qui n'ont pas été trouvé dans bio.tools sur 101:
```python
>>> Tool.objects.filter(tool_type__name="Database portal",biotoolsID="").count()
47
>>> Tool.objects.filter(tool_type__name="Database portal").count()
101
```

**Comment by bryan-brancotte** [comment]
@Aziguy tu peux évaluer combien de ces 47 serait dans FAIRsharing.org ? AgroLD y est par exemple. Peut-être qu'on aura une second méthode d'import à faire, depuis fairesharing.

**Comment by Aziguy** [comment]
| Items      | Fairsharing | 
| :---        |    :----:   | 
| Arabidopsis chloroplast database (AT_CHLORO) | Non  |
| Bacterial Genotyping | Non  |
| BactPepDB | Non  |
| BAliBASE | Oui  |
| BLC2db | Non |
| Conjdb | Non |
| CRISPRdb | Oui mais obsolète | 
| CYPedia | Non | 
| dbSTAR | Non |
| dbWFA | Non |
| Dog CNV database | Non |
| Donnée de bases | Non |
| ECOD | Non (plutôt EcoDB?) |
| eDystrophin | Non |
| EvoluCode | Non | 
| FatAndMuscleDB | Non |
| Gbrowse virus géants | Non | 
| Genolist servers | Non |
| GnplS | Non |
| GreenPhyl | Oui |
| GxDB | Oui |
| HBVdb | Non |
| HuGChip | Non |
| ICS Mouse Zoo | Non |
| KBDOCK | Non |
| Listeriomics : Systems Biology of Listeria | Non |
| Locus Specific Databases UMD | Non |
| MacSyDB-TXSSdb | Non |
| MeryB | j'ai MeRy-B |
| MouseCre | Non |
| MousePat | Mouse PATHology (MPATH) ? |
| Multi-Genome Genolist | Non |
| ORENZA | Non |
| OryGenesDB | Oui |
| OryzaTagLine | Oryza Tag Line ? |
| PhROGs | Non |
| PlantRNA | Oui |
| Podospora | Non | 
| ppRNome Browser | Non |
| PRIAM | Oui |
| SampleTracker | Non |
| secreton | Non |
| SNiPlay | Non |
| Staphylococcal regulatory RNAs | Non |
| tandemRepeat | Tandem Repeats Database ? |
| TropGene | TropGENE DB ? |
| UNIPATHWAY | UniPathway (obsolète) ? |

**Comment by bryan-brancotte** [comment]
Hi @Aziguy 

Il faudrait voir si on peut obtenir les infos via une API

**Comment by Aziguy** [comment]
> Hi @Aziguy
> 
> Il faudrait voir si on peut obtenir les infos via une API

@bryan-brancotte  j'ai réussi à créer un compte sur FAIRsharing et je souhaiterai connai
tre les informations à récupérer. Ci-dessous, un exemple : 
Merci
```
{
	"data": {
		"id": "1",
		"type": "fairsharing-records",
		"attributes": {
			"created-at": "2014-11-04T15:23:40.000Z",
			"updated-at": "2021-11-24T13:18:25.276Z",
			"legacy-ids": ["bsg-000063", "bsg-s000063"],
			"fairsharing-registry": "Standard",
			"record-type": "terminology_artefact",
			"subjects": ["Enzymology", "Life Science"],
			"domains": ["Reaction data", "Cell", "Enzyme", "Organ"],
			"taxonomies": ["All"],
			"user-defined-tags": [],
			"countries": ["Germany"],
			"name": "FAIRsharing record for: BRENDA tissue / enzyme source",
			"abbreviation": "BTO",
			"url": "https://fairsharing.org/10.25504/FAIRsharing.1414v8",
			"doi": "10.25504/FAIRsharing.1414v8",
			"fairsharing-licence": "https://creativecommons.org/licenses/by-sa/4.0/. Please link to https://fairsharing.org and https://api.fairsharing.org/img/fairsharing-attribution.svg for attribution.",
			"description": "This FAIRsharing record describes: A structured controlled vocabulary for the source of an enzyme. It comprises terms for tissues, cell lines, cell types and cell cultures from uni- and multicellular organisms.",
			"publications": [{
				"id": 9,
				"pubmed_id": 21030441,
				"title": "The BRENDA Tissue Ontology (BTO): the first all-integrating ontology of all organisms for enzyme sources.",
				"year": 2010,
				"url": "http://doi.org/10.1093/nar/gkq968",
				"authors": "Gremse M, Chang A, Schomburg I, Grote A, Scheer M, Ebeling C, Schomburg D",
				"journal": "Nucleic Acids Res.",
				"doi": "10.1093/nar/gkq968",
				"created_at": "2021-09-30T08:22:21.498Z",
				"updated_at": "2021-09-30T08:22:21.498Z"
			}, {
				"id": 1357,
				"pubmed_id": 30395242,
				"title": "BRENDA in 2019: a European ELIXIR core data resource.",
				"year": 2018,
				"url": "http://doi.org/10.1093/nar/gky1048",
				"authors": "Jeske L,Placzek S,Schomburg I,Chang A,Schomburg D",
				"journal": "Nucleic Acids Research",
				"doi": "10.1093/nar/gky1048",
				"created_at": "2021-09-30T08:24:51.780Z",
				"updated_at": "2021-09-30T11:29:06.677Z"
			}, {
				"id": 1358,
				"pubmed_id": 14681450,
				"title": "BRENDA, the enzyme database: updates and major new developments.",
				"year": 2003,
				"url": "http://doi.org/10.1093/nar/gkh081",
				"authors": "Schomburg I,Chang A,Ebeling C,Gremse M,Heldt C,Huhn G,Schomburg D",
				"journal": "Nucleic Acids Research",
				"doi": "10.1093/nar/gkh081",
				"created_at": "2021-09-30T08:24:51.872Z",
				"updated_at": "2021-09-30T11:29:06.777Z"
			}, {
				"id": 1590,
				"pubmed_id": 25378310,
				"title": "BRENDA in 2015: exciting developments in its 25th year of existence.",
				"year": 2014,
				"url": "http://doi.org/10.1093/nar/gku1068",
				"authors": "Chang A,Schomburg I,Placzek S,Jeske L,Ulbrich M,Xiao M,Sensen CW,Schomburg D",
				"journal": "Nucleic Acids Research",
				"doi": "10.1093/nar/gku1068",
				"created_at": "2021-09-30T08:25:18.284Z",
				"updated_at": "2021-09-30T11:29:14.902Z"
			}, {
				"id": 2406,
				"pubmed_id": 23203881,
				"title": "BRENDA in 2013: integrated reactions, kinetic data, enzyme function data, improved disease classification: new options and contents in BRENDA.",
				"year": 2012,
				"url": "http://doi.org/10.1093/nar/gks1049",
				"authors": "Schomburg I,Chang A,Placzek S,Sohngen C,Rother M,Lang M,Munaretto C,Ulas S,Stelzer M,Grote A,Scheer M,Schomburg D",
				"journal": "Nucleic Acids Research",
				"doi": "10.1093/nar/gks1049",
				"created_at": "2021-09-30T08:26:55.301Z",
				"updated_at": "2021-09-30T11:29:35.078Z"
			}],
			"licence-links": [{
				"licence-name": "License agreement for users of BRENDA",
				"licence-id": 490,
				"link-id": 357,
				"relation": "undefined"
			}],
			"url-for-logo": null
		}
	}
}
```

**Comment by bryan-brancotte** [comment]
Hello @Aziguy 

Bonne nouvelle !

Récupères tout ce que tu peux mettre dans le model Tool, regarde aussi s'il ont une doc, peut-être que certain champs ne sont pas affiché s'il sont vide, et qu'on pourrait les utiliser si on les trouvait.
Les subjects et domains pourrait être vue comme des keywords.

**Comment by Aziguy** [comment]
> 

url = "https://api.fairsharing.org/search/fairsharing_records?q=AgroLD"
j'obtiens un code `404` avec cet url

**Comment by bryan-brancotte** [comment]
De même, mais c'est sans s'être authentifié. Il faut je pense être authentifié pour que l'api marche. Si cela n'est toujours pas le cas il faudra les contacter car il se peut que l'api ait évolué et la doc pas encore.

**Comment by Aziguy** [comment]
@hmenager , @bryan-brancotte 
Sur les 47 db qui ne sont pas dans bio.tools voici ceux qu'on peut trouver dans FAIRsharing : 

- BAliBASE, 
- CRISPRdb, 
- GreenPhyl, 
- OryGenesDB, 
- PlantRNA, 
- PRIAM, 
- UNIPATHWAY.
L'API contient les attributs tels que :
- `"abbreviation"`,
- `"countries"`
- Etc.
Abbreviation semble représenter le `BiotoolsID`
> J'ai pu constater que si l'attribut `"countries"` contient le pays **France**, abbreviation représentera exactement la db cherché, dans le cas contraire, abbreviation représente un autre outil.
Pour l'ensemble des 7 db ci-dessus, nous avons bien **France*** dans l'attribut `abbreviation`..
> Cependant, avec la db **AgroLD**, l'API nous renvoie deux (02) outils donc l'un est au USA et l'abbreviation (_"abbreviation": "AGP format"_) ne correspond pas à  AgroLD et celui de France correspond exactement à notre recherche. J'ai effectué un test avec la db **ANISEED** pour 20 outils retourné une seule correspond et son `"countries"` est France.
