### ISSUE TITLE
Training session form: add field for training material

### ISSUE THREAD

**Issue by hchiapello** [IFB-ElixirFr/ifbcat#183]
Would it be possible to add an optional field corresponding to a link to a training material of a training session ? 
This point has been asked by ABIMS PF (Roscoff)
Thanks

**Comment by hchiapello** [comment]
ok sounds perfect with the help_text ! Thanks Bryan

**Comment by bryan-brancotte** [comment]
@Aziguy 
When creating an `Event` from a `Training`, we should also fill the `trainingMaterials` field of the `Event` with the values already in the `trainingMaterials` of the `Training`.

**Comment by Aziguy** [comment]
Done @bryan-brancotte
