### ISSUE TITLE
Add log entry when event is created with "add new session"

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#185]
TODO @bryan-brancotte add description

**Comment by Aziguy** [comment]
We already have a log entry (https://github.com/IFB-ElixirFr/ifbcat/blob/7cec054cd596d897a6d4f9a0d7988c5411ffe869/ifbcat_api/admin.py#L383) for that @bryan-brancotte. Perharps I'm wrong...

**Comment by bryan-brancotte** [comment]
You are right @Aziguy we have it [here](https://github.com/IFB-ElixirFr/ifbcat/blob/7cec054cd596d897a6d4f9a0d7988c5411ffe869/ifbcat_api/admin.py#L393-L399). We have to understand how https://catalogue.france-bioinformatique.fr/admin/ifbcat_api/event/427/change/ was created without any logentry for its creation

**Comment by Aziguy** [comment]
@bryan-brancotte  as far, regarding this issue, I didnt be able to remake it so can't know when it occur :/

**Comment by bryan-brancotte** [comment]
Hi,
So do I. Closing it and labeling ~wontfix as we were not able to reproduce it
