### ISSUE TITLE
Secure admin panel and record hacking attempts

### ISSUE THREAD

**Issue by Aziguy** [IFB-ElixirFr/ifbcat#188]
To reach to django applications, we've to use a link like https://www.appdomain.com/admin. A hacker knows in advance the page that allows access to the admin panel. 
In order to protect the admin panel of our catalog, we could make the current administration page obsolete and create a similar page (like https://www.appdomain.com/securelogin) that will allow access to the catalog administration. 
Users (hackers) who will use the obsolete page will be tracked (IP address, browser, credentials used).

What do you think about @hmenager | @bryan-brancotte

**Comment by bryan-brancotte** [comment]
Using securelogin in place of admin might mitigate some attack, but securelogin is guess-able.

Instead we could install fail2ban
