### ISSUE TITLE
OnlineOnly Boolean pertinence ?

### ISSUE THREAD

**Issue by thomasrosnet** [IFB-ElixirFr/ifbcat#190]
J'ai une question pour @hchiapello @olisand 
Pour un évènement de formation on a actuellement un true/false sur le champ OnlineOnly.

En m'occupant de faire le mapping avec le profile Bioschemas correspondant je me suis rendu compte qu'il y avait un champ "courseMode" qui correspond à OnlineOnly, mais qui accepte en valeur: "online”, “onsite” or “blend of online and onsite”.

La question: Est-ce qu'il y a souvent des formations en hybride (surtout récemment j'imagine) ? Pensez vous pertinent de changer les valeurs possible de OnlineOnly pour correspondre avec celles du profile (3 choix possible au lieux d'un true/false) ?

**Comment by olisand** [comment]
Hello,
Je ne pense pas qu'il y a déjà eu beaucoup de formations en hybride, mais effectivement ce mode tend à se généraliser. Donc, pour moi se serait une bonne idée d'avoir trois choix possibles plutôt que le booléen actuel. En plus, être au plus près de Bioschemas me semble une bonne approche.

**Comment by bryan-brancotte** [comment]
Hello @olisand , merci pour ta réponse, @Aziguy je t'assigne le ticket donc

**Comment by Aziguy** [comment]
ok

**Comment by Aziguy** [comment]
@bryan-brancotte  we should close this issue. Right?

**Comment by bryan-brancotte** [comment]
yes, closed via #193
