### ISSUE TITLE
[WIP] training material tutorial text

### ISSUE THREAD

**Issue by hmenager** [IFB-ElixirFr/ifbcat#195]
The goal of this tutorial is to explain how to proceed to create new training contents on the IFB catalogue.

# Connecting to your account...

Navigate to https://catalogue.france-bioinformatique.fr, and click on "Admin":

![image](https://user-images.githubusercontent.com/1140736/149775615-2afb9112-b133-4210-bd8a-cfe10578126c.png)

You land on this page, where you can connect to the admin page after connecting using your credentials. If you do not have any, pleas click on the "reset password", and provide your email. An password reset link will be sent to this address. If you do not receive an email, you can get support on the [IFB community support channel](https://community.france-bioinformatique.fr/c/catalogue-ifb/)

![image](https://user-images.githubusercontent.com/1140736/150177587-c2b143a7-b249-4058-a02b-b8c5abd4cab6.png)

# Adding trainings

This example shows how to first create a training, then a training event corresponding to the training, and finally some training materials, also for the same training. Please note that you should be able 

### Add a training

<strong>WHAT ARE TRAININGS: A training describes a particular ...</strong>

Go to https://catalogue.france-bioinformatique.fr/admin/, and click on "Add" in "My training"

![image](https://user-images.githubusercontent.com/1140736/150178688-51f9998c-1104-4899-b74c-8333e3649c66.png)

A form structured with 4 tabs, "Training info", "Audience", "Organizers and sponsors", and "Content" will appear

![image](https://user-images.githubusercontent.com/1140736/150180124-780358d2-4564-484a-b1a2-70c1b8fc2cc2.png)

Please note that the mandatory fields are distributed in multiple tabs:
- Name (*Training info tab*)
- Description (*Training info tab*)
- Accessibility (*Audience tab*)
- Contact Name (*Organizers and sponsors tab*)
- Contact Email
- Contact ID

![image](https://user-images.githubusercontent.com/1140736/150182417-a74447cd-0ed0-4630-80fc-2dc3af1c6c7f.png)

![image](https://user-images.githubusercontent.com/1140736/150181895-f2170e79-f62f-484f-bc2c-32bf5fab6617.png)

![image](https://user-images.githubusercontent.com/1140736/150182675-eb05f00c-f8a5-44a9-bdb4-d4223e4a6488.png)

The contact fields are, by default, filled with your user contact details. You can change these values if you aren't the contact person for the training.

**Click on "save"**

### Add a new training session corresponding to this training

<strong>
WHAT ARE TRAINING SESSIONS: A given training can take place multiple times, at different dates or in different places. Once you have described a training, you can create as many "training sessions", that will specify information such as where and when it takes place.
</strong>

You can create a new session directly from the training page (which you can access from the "Trainings" list), by clicking on "Create a new Session" on the right of the screen.

![image](https://user-images.githubusercontent.com/1140736/150183670-9cde6aa9-a812-4de2-b6f1-d75294253ee7.png)

A training session is *immediately created and saved* when you click on that button, filled with sensible default values. 

![image](https://user-images.githubusercontent.com/1140736/149818111-7641a2aa-79df-4044-8d0d-7f1c58030e8f.png)

The training session you created is immediately displayed on the [IFB training sessions webpage](https://www.france-bioinformatique.fr/formations-catalogue/).

### Add training materials

<strong>
WHAT ARE TRAINING MATERIALS: These are the materials (slides, documents, repositories) distributed or accessed for the purpose of training.
</strong>

To add some training material, click on the corresponding link in the left menu

![image](https://user-images.githubusercontent.com/1140736/150635487-257fb7fd-c9bf-4e6e-902a-61a1ac822c9d.png)

Then click on the "Add training material" button to the top right of the screen:

![image](https://user-images.githubusercontent.com/1140736/150635525-b571a63d-40ec-4ce3-b3ca-dd6ea1204648.png)

Fill all the relevant fields (the only mandatory ones are name, description, file name and file description).

![image](https://user-images.githubusercontent.com/1140736/150635815-d73a13bc-c17f-4852-9b33-eb7874a0a13b.png)

**Comment by hmenager** [comment]
the text above is to be added to the wiki, once ~ finalized. Working on it directly with issues, because editor allows pasting images.

**Comment by hmenager** [comment]
now available in https://github.com/IFB-ElixirFr/ifbcat/wiki/training_tutorial

**Comment by olisand** [comment]
Mauvais lien... c'est celui-ci: https://github.com/IFB-ElixirFr/ifbcat/wiki/Training-tutorial
