### ISSUE TITLE
Use Licence model for Tool

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#205]
Once #204 is merged, it would be interesting to use the model for tools in place of the CharField we [currently have](https://github.com/IFB-ElixirFr/ifbcat/blob/1b67a31d12f9618879236153c1924286254c2b6e/ifbcat_api/model/tool/tool.py#L52)

**Comment by Aziguy** [comment]
> Once #204 is merged, it would be interesting to use the model for tools in place of the CharField we [currently have](https://github.com/IFB-ElixirFr/ifbcat/blob/1b67a31d12f9618879236153c1924286254c2b6e/ifbcat_api/model/tool/tool.py#L52)

Done!

**Comment by bryan-brancotte** [comment]
> > Once #204 is merged, it would be interesting to use the model for tools in place of the CharField we [currently have](https://github.com/IFB-ElixirFr/ifbcat/blob/1b67a31d12f9618879236153c1924286254c2b6e/ifbcat_api/model/tool/tool.py#L52)
> 
> Done!

Good :) I like to provide the commit sha to help finding how it is/was done. You also can add `closes #205` in the description of the commit, really help later when digging.

**Comment by Aziguy** [comment]
@bryan-brancotte  please could you let me know what's going wrong [here](https://github.com/IFB-ElixirFr/ifbcat/blob/improve-tools-model/ifbcat_api/migrations/0172_merge_0170_auto_20220104_2356_0171_auto_20220124_1118.py#:~:text=def%20migrate_tool_license(apps,tool.save())
