### ISSUE TITLE
deleting a training where training events have been created

### ISSUE THREAD

**Issue by froggypaule** [IFB-ElixirFr/ifbcat#209]
Sorry, don't seem to have acces to community :( 

Situation:
- created a training 'Paulette's test'
- created a training session 'New session of paule's test' depending on this training
- deleted  training 'Paulette's test'
- 'New session of paule's test'  still exists
  
So maybe this is expected, so this is rather a question for you? Thanks!

**Comment by froggypaule** [comment]
maybe there is no relationship between training and event?

**Comment by bryan-brancotte** [comment]
Hi, 
We allow to delete the training and keep the event associated [src](https://github.com/IFB-ElixirFr/ifbcat/blob/861cdebc1cb2e080fcfd737fb197bb03c36b648e/ifbcat_api/model/event.py#L332)

**Comment by froggypaule** [comment]
ok, thanks for this.

**Comment by froggypaule** [comment]
Actually I reopen this: it is not clear what the relationship between trainings and events are?
SInce, we can create events in two ways: in dashboard, either via Trainings, via dashboard / Add Events.

How are do there two created events differ?

**Comment by bryan-brancotte** [comment]
Via "Add Events" the event is pre-filled with information from the training.

In both case a user have to provide the training if the event is a TrainingSession, but in order to prevent to big data deletion, we allow to delete the training while preserving the event.

**Comment by froggypaule** [comment]
Ah! yes, I see: it is enough to properly set the type of event (ie training session), so it makes all sense. Thanks!
