### ISSUE TITLE
Serialising entity:entity references within the data

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#21]
This in follow-up to https://github.com/joncison/ifbcat-sandbox/pull/18

@bryan-brancotte and me agree that, where we one object property is a reference to another object, then the corresponding field should be represented as a link to that object, rather than the string representation of the object (typically a name).  For example in the Event object, this:

```
 "elixirPlatforms": [
        "http://127.0.0.1:8000/api/elixirplatform/Data/",
        "http://127.0.0.1:8000/api/elixirplatform/Tools/"
    ],
    "communities": [
        "http://127.0.0.1:8000/api/community/Galaxy/"
    ],
    "hostedBy": [
        "http://127.0.0.1:8000/api/organisation/The%20Institut%20Pasteur/"
    ]
```

rather than:
```
 "elixirPlatforms": [
        "Data",
        "Tools"
    ],
    "communities": [
        "Galaxy"
    ],
    "hostedBy": [
        "The Institut Pasteur"
    ]
```

Probably a no-brainer.  But it's a basic design decision, so please @hmenager let us know you're happy with it (pls. accept the invite to the project, and I'll assign this issue to you).

**Comment by bryan-brancotte** [comment]
Following #18 I have used with 3f727be the HyperlinkedModelSerializer which by default use hyperlink in place of pk or other slug, producing proposed output herebefore.

**Comment by joncison** [comment]
Nice.  I created https://github.com/joncison/ifbcat-sandbox/issues/21 just so Herve can see what we're doing, but I agree this is the right way to go.

**Comment by joncison** [comment]
@hmenager, please take a look, I think what we've done is right, but pls. confirm and close or comment.
