### ISSUE TITLE
elixir-platforms dropdown list not working in one instance

### ISSUE THREAD

**Issue by froggypaule** [IFB-ElixirFr/ifbcat#211]
![Screenshot from 2022-01-24 15-18-20](https://user-images.githubusercontent.com/47455219/150799920-ee8c991e-72e7-4bef-919d-0d04c184a231.png)

As shown above.
But it works if one clicks to '+' to add another platform.

**Comment by bryan-brancotte** [comment]
Indeed no platforms are provided yet

**Comment by froggypaule** [comment]
ok thanks!
