### ISSUE TITLE
Allows creating a copy of a training

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#220]
Django allows having a button easily

**Comment by Aziguy** [comment]
@bryan-brancotte  there's not a description for this issue?

**Comment by bryan-brancotte** [comment]
En effet je n'ai pas été généreux en explication. Durant le catathon il à été demandé si l'on pouvait copier un training car certaine info était souvent les mêmes. Django permet assez simplement d'ajouter la possibilité de copier un objet dans l'interface d'admin. Je te propose de chercher comment si cela te vas.

**Comment by Aziguy** [comment]
ok got it 👍🏾

**Comment by Aziguy** [comment]
@bryan-brancotte 
We should close this issue. Right?

**Comment by bryan-brancotte** [comment]
Yes, If you had added `closes #220` in https://github.com/IFB-ElixirFr/ifbcat/pull/222 it would have been done automatically on merge
