### ISSUE TITLE
Slug name of tool in admin

### ISSUE THREAD

**Issue by Aziguy** [IFB-ElixirFr/ifbcat#242]
From admin, we can access to each detail of a tool (json format) in clicking on a link ; which will redirect us to the details of the selected tool.
Right now, it seems the it's the name of tool which is atached to the link. This raise an issue when the tool has some spaces. We should change `name`  by `BiotoolsID`  to avoid any issue.

**Comment by bryan-brancotte** [comment]
duplicate and subsumed by #240
