### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by Aziguy** [IFB-ElixirFr/ifbcat#246]
Any user can access and change informations of another user. Only an user of group should be able to edit informations related to its member.

**Comment by bryan-brancotte** [comment]
Permissions can be observed at https://github.com/IFB-ElixirFr/ifbcat/blob/master/ifbcat_api/model/userProfile.py#L156-L162

A staff user can indeed edit any user, but only iff this user is not a staff either. Documentation would be needed
