### ISSUE TITLE
Trainer form

### ISSUE THREAD

**Issue by Aziguy** [IFB-ElixirFr/ifbcat#250]
We should improve [this form](https://catalogue.france-bioinformatique.fr/admin/ifbcat_api/trainer/add/) that way : 

1. User fill `TrainerId`
2. The system autopopulates `TrainerName`  and  `TrainerEmail` related to `TrainerId`  filled by user.

**Comment by bryan-brancotte** [comment]
Now that staff user can create user, we should only user UserProfil instance, both TrainerSomething and ContactSomething will have to be reworked
