### ISSUE TITLE
makdown in some forms

### ISSUE THREAD

**Issue by Aziguy** [IFB-ElixirFr/ifbcat#251]
use a markdown editor, or a graphical editor that generates markdown on some forms (Teams/ Platforms). But this should be able to propagate to all fields which might be a bit long and enriched.
> check if from front end there will easy to handle it !

**Comment by bryan-brancotte** [comment]
Writing markdown in a textArea is already possible. The issue here is that frontend will then have to interpret markdown i.e @Sylmila

**Comment by bryan-brancotte** [comment]
@Sylmila 

I added an API to convert on the fly md to html

https://github.com/IFB-ElixirFr/ifbcat/pull/253

```
curl --location --request POST 'https://catalogue.france-bioinformatique.fr/api/md-to-html/' \
--header 'Accept: text/html' \
--header 'Content-Type: application/json' \
--data-raw '{"md": "# ee\n* a\n * [aa](https://aaa.com)" }'

<h1>ee</h1>
<ul>
<li>a</li>
<li><a href="https://aaa.com">aa</a></li>
</ul>
```

**Comment by bryan-brancotte** [comment]
need a con

**Comment by bryan-brancotte** [comment]
soon to be released @Aziguy :

```
curl --location --request POST 'https://catalogue.france-bioinformatique.fr/api/md-to-html/' \
--header 'Accept: text/html' \
--header 'Content-Type: application/json' \
--data-raw '{"md": "IyBlCgogKiBhCiAqIFthYV0oaHR0cHM6Ly9hYS5jb20vKQo=", "encoding": "base64"}'

<h1>e</h1>
<ul>
<li>a</li>
<li><a href="https://aa.com/">aa</a></li>
</ul>
```
