### ISSUE TITLE
Refactor duplicated validate_topics functionality

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#30]
Multiple objects will need validation of EDAM topic URIs.

Currently ``validate_topics`` is implemented / duplicated on ``ProjectSerializer`` and ``EventSerializer`` 

Code refactor is needed to keep the code DRY.

**Comment by joncison** [comment]
Also now in ``BioinformaticTeamSerializer``

**Comment by joncison** [comment]
Hi @bryan-brancotte 

I think you addressed this in https://github.com/IFB-ElixirFr/ifbcat/commit/ff3cdbedc8f52ae85500ba7eacaacc1d3ee2ee23, so please close this issue if you're happy.

**Comment by bryan-brancotte** [comment]
yes indeed,
