### ISSUE TITLE
Event's Organizer should be human readable in tess 

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#305]
Spotted by @olisand 

https://tess.elixir-europe.org/events/4th-workshop-single-cell-sincellte-2022-single-cell-transcriptomics-spatial-and-multi-omics

**Comment by bryan-brancotte** [comment]
Renderer should be adapted to handle subnode with M2M ([here for Single sub node](https://github.com/IFB-ElixirFr/ifbcat/blob/34ee891befa1c3c41a4a4e910954762e69207d42/ifbcat_api/renderers.py#L112-L124))

**Comment by bryan-brancotte** [comment]
Then in get_rdf_mapping put something like

```
organisedByTeams=dict(schema_attr='organizer', _fields=dict(
         name='name',
         url='homepage',
 ), _type="Organization"),
```

**Comment by bryan-brancotte** [comment]
Todo : is tess using all organizers ? Seen only one in https://tess.elixir-europe.org/events/bigomics-genomique-comparative-biopolis while multiple when looking at api : https://catalogue.france-bioinformatique.fr/api/event/591/?format=json-ld

**Comment by olisand** [comment]
TeSS answer: currently the scraper will probably just take the first or last one.
I added an issue on their main repo.

**Comment by olisand** [comment]
Extract multiple organizers (comma-separated) solved on TeSS side: https://github.com/ElixirTeSS/TeSS/issues/914

**Comment by bryan-brancotte** [comment]
Good news ! I'm keeping the issue open until we observe that the event have indeed multiple organizer

**Comment by olisand** [comment]
Absolutely! But even then, this side issue (organizer names should be scrapped instead of object URLs) will not be fixed yet, or am I wrong?

**Comment by bryan-brancotte** [comment]
Yes, we ill have to include the organizers with additional nodes as it is done with the postal address

**Comment by bryan-brancotte** [comment]
Applied in prod, can be seen at https://catalogue.france-bioinformatique.fr/api/event/476/?format=json-ld

@olisand  I keep it open to follow it everything works with tess now

**Comment by olisand** [comment]
@bryan-brancotte Not yet ok on TeSS. Organizer now shows the name of the event, still followed by urls corresponding to organizer(s) instead of organizer name(s). Example here: https://tess.elixir-europe.org/events/introduction-a-l-analyse-de-donnees-transcriptomiques-avec-galaxy

**Comment by bryan-brancotte** [comment]
Hi @olisand 

Applied in prod : https://catalogue.france-bioinformatique.fr/api/event/637/?format=json-ld

Again I keep it open to follow it everything works with tess now

**Comment by olisand** [comment]
Hello @bryan-brancotte 
It looks good on TeSS, nice job. Thanks!
