### ISSUE TITLE
Support generation of OpenAPI docs

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#50]
See https://www.django-rest-framework.org/api-guide/schemas/

**Comment by bryan-brancotte** [comment]
With @thomasrosnet and @mrcrony  we did it with e84870b

**Comment by bryan-brancotte** [comment]
can be seen at https://catalogue.france-bioinformatique.fr/swagger-ui/ and https://catalogue.france-bioinformatique.fr/openapi/
