### ISSUE TITLE
Are discrepancies between name and human-readable labels safe?

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#52]
Check that discrepany in name and human-readable label is safe for all practical purposes:  

Sometimes discrepancies are unavoidable as in the following cases:

BIOINFO = '3D-BioInfo', _('3D-BioInfo')
PROFESSIONAL_INITIAL = 'Professional (initial)', _('Professional (initial)')    
PROFESSIONAL_CONTINUED = 'Professional (continued)', _('Professional (continued)')

**Comment by joncison** [comment]
Also in ``IfbMembershipType``

**Comment by bryan-brancotte** [comment]
IfbMembershipType reworked, community is free to fill
