### ISSUE TITLE
Add logo field to EventSponsor model

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#65]
logo 
Logo of the sponsor.
image
1 only

**Comment by joncison** [comment]
Good if you could take this one, Bryan!  See also https://github.com/joncison/ifbcat-sandbox/issues/27, https://github.com/joncison/ifbcat-sandbox/issues/76 and https://github.com/joncison/ifbcat-sandbox/issues/44  (all the same thing).  

I left it because a file (the image) needs to be stored somewhere/somehow, and I didn't get around to looking into how to do that.

Thanks!

**Comment by bryan-brancotte** [comment]
Hi @joncison 

Indeed we might need to store the image in the filesystem in [MEDIA_ROOT](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-MEDIA_ROOT), or save it as binary in the databases. I know the first way, not the second.

But maybe we could just ask for an url to the logo ? We would neither have to store and serve anything, nor rendering a binary image. What do you think of the "hack-ish" solution ?

**Comment by joncison** [comment]
As discussed this AM, agree we can just store the logo URL, and deal with any issues (around scaling etc.) as they arise.

**Comment by joncison** [comment]
nb. field name is "logo_url" consistently, rather than "logo"
