### ISSUE TITLE
Refactor unitId field of BioinformaticsTeam model to enum (maybe) 

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#72]
``unitId`` is currently defined as a string, but it could be better if it was an enum

Depends on the data (to look into)

**Comment by joncison** [comment]
@hmenager @thomasrosnet do we have a list of "unit IDs" somewhere?

**Comment by thomasrosnet** [comment]
i don't think i have one

**Comment by bryan-brancotte** [comment]
should not be an enum as new value would require codebase changes, if needed a foreign key were only curator can add/remove value should be considered.
