### ISSUE TITLE
Refactor validate_orgid to keep code DRY

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#75]
The functionality / code is now duplicated in ``OrganisationSerializer`` and BioinformaticTeamSerializer``

**Comment by joncison** [comment]
Hi @bryan-brancotte 

What is the best-practice way to refactor the code, such that all (or at least all re-used) validation logic is in one place?

I notice in bio.tools there is [validators.py](https://github.com/bio-tools/biotoolsRegistry/blob/master/backend/elixir/validators.py) which seems sensible.   There's also some code in there (esp. ontology validation) that looks useful.

**Comment by bryan-brancotte** [comment]
Hi @joncison 

I think the approach used in the link you provided is the right way. Such refactoring would also allow us to use this validator within the model, an thus use them in the admin ui. For now admin can create Organization with a DOI='toto'.

In general we should refactor validator in this way, and use them both in model and serializer.

Maybe we could even by default ask the serializer to validate with the model:
```
class XXXSerializer(serializers.ModelSerializer):

    def validate(self, attrs):
        self.Meta.model(**attrs).clean_fields()
        self.Meta.model(**attrs).clean()
        return attrs
```

**Comment by joncison** [comment]
OK, cool.  And yes, very good idea with the code snippet.

Does that mean we'd need to override the ``clean`` method (within each model) to call the validation logic within ``validators.py``), as required?

**Comment by bryan-brancotte** [comment]
I found out that I was wrong and DRF uses models the validators ! So I did not have to use the snippet.

We could also add a validator for the DOI

While I was "in" models I took some time to remove wildcard import with d54b5ae425aef4a430219d72209a6c8e9b49f9f7 They sometime can cause issue when multiple file import resources that are different but with the same name

**Comment by bryan-brancotte** [comment]
_I forgot to answer the question._

We don't need to override the clean method, we just provide the validators for fields that need some, and the clean*() methods of Model take care of the rest.

**Comment by joncison** [comment]
OK, nice !  Will take a look ...

**Comment by joncison** [comment]
Solution is very nice @bryan-brancotte, so please close this if you're happy.
