### ISSUE TITLE
Ensure API will support query by specific tag

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#90]
We want to retrieve COVID-relevant resources from the catalogue.

"COVID" could be an EDAM topic term, in which case the query becomes a general one over the relevant fields (i.e. which use the EDAM Topic) such as ``expertise`` in ``Team`` model, ``topics`` in ``TrainingMaterial`` model etc.

**Comment by joncison** [comment]
I just tested this.    The following entities have a ``keyword`` attribute:

* BioinformaticsTeam
* TrainingMaterial
* Event
* TrainingEvent

thus so long as we define a tag e.g. "COVID-19" then these relevant resources can be retrieved, e.g.
http://127.0.0.1:8000/api/trainingmaterial/?search=COVID-19

It also works with multiple keywords in a logical AND sort of way, e.g. the following will retrieve resources only if they have the keyword "COVID-19" AND "keyword2":
http://127.0.0.1:8000/api/trainingmaterial/?search=COVID-19&search=Keyword2

It would also work if the "COVID-19" etc. was defined via EDAM (i.e. in ``topics`` field) rather than ``keyword`` field, however see https://github.com/joncison/ifbcat-sandbox/issues/92.

**Comment by joncison** [comment]
cc @jvanheld @hmenager 

Do you agree the above is adequate for retrieving COVID-19 relevant resources from the catalogue (although see also #92).  If so I'll close this issue, thanks!

**Comment by hmenager** [comment]
I agree with you @joncison _except_ for creating COVID-19 as an EDAM term. COVID-19 being a disease rather than a bioinformatics concept, it is outside the scope of EDAM IMO. To identify COVID-19 related resources, I'd use either a sort of tag, or another ontology (for disease, MONDO is probably the best option).

**Comment by mrcrony** [comment]
Hello,
I just tested :
https://catalogue.france-bioinformatique.fr/api/event/2/?search=COVID-19

Got a 500.
I did create an event, assigned 2 keywords.
What am I missing ?
Cheers

**Comment by joncison** [comment]
The 500 issue has been fixed and we agree to tag "COVID-19" as a keyword to above entities (if support for tagging other entities is required in future, it could be easily addded)
