### ISSUE TITLE
Decide on behaviour of EDAM URI fields

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#92]
Sensible to have the EDAM concept URIs e.g. http://edamontology.org/operation_0416, in the database, as these are unique/persistent.

But for search purposes, it would be good also to render the corresponding term, e.g. "Epiptope mapping".

This probably means we need to introduce a model for EDAM concept that includes the URI and term, only have the URI editable by users, but serialise both the URI and term to JSON, and support filtering over both.  

Then refactor the code to use this model.

cc @hmenager & @bryan-brancotte for an opinion.

**Comment by bryan-brancotte** [comment]
We can add new fields to Topic such as name, but we should also add `Exact synonyms`, deprecation status, and maybe description. 

We can make a management command (`python manage.py do_something_on_topic`) that will fetch all missing information for topic in the DB. We can also import all the topics in the DB, it will allow user to search for topics to associated with their BioinformaticsTeam/Event/... within the application.

**Comment by joncison** [comment]
Excellent, agree with all above.  A fair bit of work involved, so I think we should do this once we've closed as many of the other (easier) open issues.

**Comment by bryan-brancotte** [comment]
done
