### ISSUE TITLE
Consider adding a field to relate Person to Community

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#95]
Currently there's no User::Community relation.

It would be nice to add a field to support this, to allow people to identify who the FR local contacts are for a given community.

What do you think @hmenager ?

**Comment by joncison** [comment]
I think this should be "Coordinator" *i.e.* the FR-local contact / coordinator of the community.

**Comment by bryan-brancotte** [comment]
will be added if needed
