### ISSUE TITLE
kick start unit testing

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/ifbcat#97]
We are starting to have a code base big enough to introduce new bug when fixing others, I hope I did not with d54b5ae425aef4a430219d72209a6c8e9b49f9f7. If you are ok with that, I try to initiate something simple based on json.

**Comment by joncison** [comment]
I agree, this is needed for the future maintenance / extension of the system.  Perhaps to-do once more of the (easier) tickets are closed?

**Comment by bryan-brancotte** [comment]
Hi @joncison 

I think this is issue is quite importante, I would say High priority. I'm starting to work on it.

Cheers,

**Comment by bryan-brancotte** [comment]
kick started, not perfect, but working
