### ISSUE TITLE
Import of "Platform" data (to BioinformaticsTeam)

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#99]
# Overarching issues 
- [ ] confirm that all of these Platforms are still active, and should become BioinformaticsTeam

# Existing fields (in "Platform")
## Name
**Mapping:**  BioinformaticsTeam:name
**Issues:** None, but note that are used for database look-up and thus must comply to ``regex=r'^[a-zA-Z0-9 \-_~]+$'`` (all of Platform:name do, so no problem)

## Postal address
**Mapping:** BioinformaticsTeam:address
**Issues:** 
- [x] edit addresses before import, to fix strange characters
  - *[this was an issue with Excel CSV]* 
- [ ] edit addresses before import, to  and add commas between address components
  - *[this must be fixed at Drupal export level - it's erroneoulsy removing `\n`]*

## Affiliation
**Mapping:** BioinformaticsTeam:affiliatedWith 
**Issues:**
- [ ] to populate this require an Organisation object for each affiliation; mandatory fields are *name*, *description* and *homepage*.  Decide what to do!
  - *[for now we trust the names listed in the columns are correct organisation name (note that names must satisfy the regex ``regex=r'^[a-zA-Z0-9 \-_~]+$'``), and add boilerplate values for description and homepage]*
- [ ] data clean-up; current values are a mix of institute abbreviations/names, and partial addresses. Is this right? Is there an issue with the CSV?
  - *[the data is very messy - must discuss with Jacques how this should be cleaned-up, either before or after import to new system]*
- [ ] add missing values (for "INCa-SLC" and "South Green")

## Website
**Mapping:** BioinformaticsTeam:homepage
**Issues:**
- [ ] add missing values; only 4 Platform have URLs (BioinformaticsTeam:homepage is mandatory)
- [ ] ensure URLs are in correct syntax, *i.e.* with "http(s)" prefix (not all are) 

## Scientific responsibility
**Mapping:** BioinformaticsTeam:scientificLeader (UserProfile)
**Issues:**
- [ ] to populate this would require a UserProfile object, *i.e.* a user account, for each named person; mandatory fields are *firstName*, *lastName*, *email* and *password*.  We have in most cases *firstName* and *lastName* but no emails. 
 Decide what to do!
- [ ] data clean-up; ensure consistent capitalisation (it's mixed currently)
- [ ] data clean-up; add missing values (for PRABI-HCL and Orphanet) (although BioinformaticsTeam:scientificLeader is not mandatory)
- [ ] change the model; BioinformaticsTeam:scientificLeader cardinality is "0 or 1" currently, however one Platform has two scientific leaders listed.

## Technical responsibility
**Mapping:** BioinformaticsTeam:technicalLeader (UserProfile)
**Issues:**
- [ ] creation of UserProfile objects (as above)
- [ ] data clean-up; remove instances of "Responsable opÃ©rationnelNon renseignÃ©" *etc.* (this might be an issues with the CSV)
- [ ] data clean-up; ensure consistent capitalisation (it's mixed currently)
- [ ] data clean-up; add missing values (for PRABI-HCL) (although BioinformaticsTeam:technicalLeader is not mandatory)
- [ ] if we expect one Platform to have two or more technical leaders, then change the model; BioinformaticsTeam:technicalLeader cardinality is "0 or 1" currently.

## Certificate(s)
**Mapping:** BioinformaticsTeam:certification
**Issues:**
- [ ] data clean-up; very messy data (this could be issue with CSV), only two platforms appear to have certificates - look into this

## Structure
**Mapping:** BioinformaticsTeam:unitId ?   
**Issues:**
- [ ] identify the correct mapping, BioinformaticsTeam:unitId is *"Unit ID (unique identifier of research or service unit) that the Bioinformatics Team belongs to."*.  If not this, then what?
- [ ] data clean-up; "Non renseignÃ©e" is given for some fields
- [ ] change the model as necessary, some Platform have multiple "Structure" values, but BioinformaticsTeam:unitId cardinality is "0 or 1" currently, 

## Team
**Mapping:** BioinformaticsTeam:leader ?   
**Issues:**
- [ ] identify the correct mapping, BioinformaticsTeam:leader is *"Leader of the team."* - is that good?
- [ ] data clean-up; add missing values (for P3M) (although BioinformaticsTeam:leader is not mandatory)
- [ ] data clean-up; ensure consistent capitalisation (it's mixed currently)
- change the model as necessary, some Platform have multiple "Team" values, but BioinformaticsTeam:leader cardinality is "0 or 1" currently, 

## Path
**Mapping:** BioinformaticsTeam:logo
**Issues:** 
- [ ] data clean-up; check the URLs actually resolve to an appropriate image.

# Additional MANDATORY fields (in "BioinformaticsTeam")

## description 
*"Short description of the team."*
**Issues:**
- [ ] see if these exist anywhere
- [ ] decide on curation mechanism (assuming description should remain mandatory - I think it should)

## members
*"Members of the team."*
**Issues:**
- [ ] should this be made optional, in the short-term?  It would be expensive to populate team members (which would have to be UserProfile / user accounts in a reasonable way.

## maintainers
*"Maintainer(s) of the team metadata in IFB catalogue."*
- [ ] decide if this should remain mandatory, I think it should.  
- [ ] if mandatory, who?  Would need to create a UserProfile/user account for each maintainer.

## orgid
*"Organisation ID (GRID or ROR ID) of the bioinformatics team."*
- [x] make this optional in short term? 
  - *[Yes, make it optional]*

## ifbMembership
*"Type of membership the bioinformatics team has to IFB."*
- [ ] should remain mandatory - need to assign values one of "IFB platform", "IFB-associated team" or "Not a member".  Always "IFB platform"?

## fundedBy
*"Organisation(s) that funds the bioinformatics team."*
- [ ] make this optional in short term?

**Comment by bryan-brancotte** [comment]
model imported
